packages:
  - 'tests/e2e'

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  lightningcss: true
  nx: true
  sharp: true
  unrs-resolver: true

peerDependencyRules:
  allowedVersions:
    'lucide-preact>preact': '11.0.0'
