// <auto-generated />
using System;
using System.Text.Json;
using Hotel.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20260924171116_InitialCatalog")]
    partial class InitialCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hotel.Api.Data.AdminUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasAlternateKey("Email")
                        .HasName("admin_users_email_unique");

                    b.ToTable("admin_users", (string)null);
                });

            modelBuilder.Entity("Hotel.Api.Data.Amenity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AppliesTo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("both")
                        .HasColumnName("applies_to");

                    b.Property<string>("Category")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("services")
                        .HasColumnName("category");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("sparkles")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name")
                        .HasName("amenities_name_unique");

                    b.ToTable("amenities", (string)null);
                });

            modelBuilder.Entity("Hotel.Api.Data.BlogPost", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("author");

                    b.Property<JsonDocument>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Excerpt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("excerpt");

                    b.Property<string>("HeroImage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hero_image");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("SeoDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("seo_description");

                    b.Property<string>("SeoTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("seo_title");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("draft")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Slug" }, "blog_posts_slug_idx")
                        .IsUnique();

                    b.ToTable("blog_posts", (string)null);
                });

            modelBuilder.Entity("Hotel.Api.Data.Destination", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<JsonDocument>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Eyebrow")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Destination")
                        .HasColumnName("eyebrow");

                    b.Property<string>("HeroImage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hero_image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("SeoDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("seo_description");

                    b.Property<string>("SeoTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("seo_title");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("draft")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Slug" }, "destinations_slug_idx")
                        .IsUnique();

                    b.ToTable("destinations", (string)null);
                });

            modelBuilder.Entity("Hotel.Api.Data.Hotel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("USD")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DestinationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination_id");

                    b.Property<string>("HeroImage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hero_image");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("PriceFrom")
                        .HasColumnType("integer")
                        .HasColumnName("price_from");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Boutique hotel")
                        .HasColumnName("property_type");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("published_at");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision")
                        .HasColumnName("rating");

                    b.Property<int>("ReviewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("review_count");

                    b.Property<string>("SeoDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("seo_description");

                    b.Property<string>("SeoTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("seo_title");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<int?>("StarRating")
                        .HasColumnType("integer")
                        .HasColumnName("star_rating");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("draft")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DestinationId" }, "hotels_destination_idx");

                    b.HasIndex(new[] { "Status", "PriceFrom", "Rating" }, "hotels_search_idx");

                    b.HasIndex(new[] { "Slug" }, "hotels_slug_idx")
                        .IsUnique();

                    b.ToTable("hotels", (string)null);
                });

            modelBuilder.Entity("Hotel.Api.Data.HotelAmenity", b =>
                {
                    b.Property<string>("HotelId")
                        .HasColumnType("text")
                        .HasColumnName("hotel_id");

                    b.Property<string>("AmenityId")
                        .HasColumnType("text")
                        .HasColumnName("amenity_id");

                    b.HasKey("HotelId", "AmenityId")
                        .HasName("hotel_amenities_hotel_id_amenity_id_pk");

                    b.HasIndex("AmenityId");

                    b.ToTable("hotel_amenities", (string)null);
                });

            modelBuilder.Entity("Hotel.Api.Data.HotelFact", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("group");

                    b.Property<string>("HotelId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hotel_id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "HotelId", "SortOrder" }, "hotel_facts_hotel_sort_idx");

                    b.ToTable("hotel_facts", (string)null);
                });

            modelBuilder.Entity("Hotel.Api.Data.HotelFaq", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("answer");

                    b.Property<string>("HotelId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hotel_id");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "HotelId", "SortOrder" }, "hotel_faqs_hotel_sort_idx");

                    b.ToTable("hotel_faqs", (string)null);
                });

            modelBuilder.Entity("Hotel.Api.Data.HotelGalleryImage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Alt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("alt");

                    b.Property<string>("Caption")
                        .HasColumnType("text")
                        .HasColumnName("caption");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("HotelId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hotel_id");

                    b.Property<string>("RoomId")
                        .HasColumnType("text")
                        .HasColumnName("room_id");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<string>("Src")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("src");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex(new[] { "HotelId", "SortOrder" }, "hotel_gallery_images_hotel_sort_idx");

                    b.ToTable("hotel_gallery_images", (string)null);
                });

            modelBuilder.Entity("Hotel.Api.Data.HotelHighlight", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("HotelId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hotel_id");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "HotelId", "SortOrder" }, "hotel_highlights_hotel_sort_idx");

                    b.ToTable("hotel_highlights", (string)null);
                });

            modelBuilder.Entity("Hotel.Api.Data.HotelNearbyPlace", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<int>("DistanceMeters")
                        .HasColumnType("integer")
                        .HasColumnName("distance_meters");

                    b.Property<string>("HotelId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hotel_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "HotelId", "SortOrder" }, "hotel_nearby_places_hotel_sort_idx");

                    b.ToTable("hotel_nearby_places", (string)null);
                });

            modelBuilder.Entity("Hotel.Api.Data.HotelPolicy", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("HotelId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hotel_id");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "HotelId", "SortOrder" }, "hotel_policies_hotel_sort_idx");

                    b.ToTable("hotel_policies", (string)null);
                });

            modelBuilder.Entity("Hotel.Api.Data.HotelReview", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("GuestCountry")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("guest_country");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("guest_name");

                    b.Property<string>("HotelId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hotel_id");

                    b.Property<int>("Nights")
                        .HasColumnType("integer")
                        .HasColumnName("nights");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision")
                        .HasColumnName("rating");

                    b.Property<string>("Response")
                        .HasColumnType("text")
                        .HasColumnName("response");

                    b.Property<string>("ReviewedAt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("RoomId")
                        .HasColumnType("text")
                        .HasColumnName("room_id");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<string>("StayedAt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stayed_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("TravelerType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("traveler_type");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex(new[] { "HotelId", "SortOrder" }, "hotel_reviews_hotel_sort_idx");

                    b.ToTable("hotel_reviews", (string)null);
                });

            modelBuilder.Entity("Hotel.Api.Data.HotelReviewScore", b =>
                {
                    b.Property<string>("HotelId")
                        .HasColumnType("text")
                        .HasColumnName("hotel_id");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<double>("Score")
                        .HasColumnType("double precision")
                        .HasColumnName("score");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.HasKey("HotelId", "Category")
                        .HasName("hotel_review_scores_hotel_id_category_pk");

                    b.HasIndex(new[] { "HotelId", "SortOrder" }, "hotel_review_scores_hotel_sort_idx");

                    b.ToTable("hotel_review_scores", (string)null);
                });

            modelBuilder.Entity("Hotel.Api.Data.Inquiry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("Adults")
                        .HasColumnType("integer")
                        .HasColumnName("adults");

                    b.Property<string>("CheckIn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("check_in");

                    b.Property<string>("CheckOut")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("check_out");

                    b.Property<int>("Children")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("children");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("HotelId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hotel_id");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("OfferId")
                        .HasColumnType("text")
                        .HasColumnName("offer_id");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("RoomId")
                        .HasColumnType("text")
                        .HasColumnName("room_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("new")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("OfferId");

                    b.HasIndex("RoomId");

                    b.HasIndex(new[] { "Status", "CreatedAt" }, "inquiries_status_idx");

                    b.ToTable("inquiries", (string)null);
                });

            modelBuilder.Entity("Hotel.Api.Data.MediaAsset", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Alt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("alt");

                    b.Property<string>("Caption")
                        .HasColumnType("text")
                        .HasColumnName("caption");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("filename");

                    b.Property<double>("FocalX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.5)
                        .HasColumnName("focal_x");

                    b.Property<double>("FocalY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.5)
                        .HasColumnName("focal_y");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mime_type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<JsonDocument>("Variants")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("variants");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.ToTable("media_assets", (string)null);
                });

            modelBuilder.Entity("Hotel.Api.Data.Offer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("DiscountPercent")
                        .HasColumnType("integer")
                        .HasColumnName("discount_percent");

                    b.Property<string>("HotelId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hotel_id");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("draft")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("Terms")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("terms");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ValidFrom")
                        .HasColumnType("text")
                        .HasColumnName("valid_from");

                    b.Property<string>("ValidTo")
                        .HasColumnType("text")
                        .HasColumnName("valid_to");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "HotelId", "Slug" }, "offers_hotel_slug_idx")
                        .IsUnique();

                    b.ToTable("offers", (string)null);
                });

            modelBuilder.Entity("Hotel.Api.Data.PageSnapshot", b =>
                {
                    b.Property<string>("Path")
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<string>("AssetVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("asset_version");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("generated_at");

                    b.Property<string>("Html")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("html");

                    b.HasKey("Path");

                    b.ToTable("page_snapshots", (string)null);
                });

            modelBuilder.Entity("Hotel.Api.Data.Room", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Bed")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bed");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("HotelId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hotel_id");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<int>("MaxGuests")
                        .HasColumnType("integer")
                        .HasColumnName("max_guests");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("PriceFrom")
                        .HasColumnType("integer")
                        .HasColumnName("price_from");

                    b.Property<int?>("SizeSqm")
                        .HasColumnType("integer")
                        .HasColumnName("size_sqm");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("draft")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "HotelId", "Slug" }, "rooms_hotel_slug_idx")
                        .IsUnique();

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("Hotel.Api.Data.RoomAmenity", b =>
                {
                    b.Property<string>("RoomId")
                        .HasColumnType("text")
                        .HasColumnName("room_id");

                    b.Property<string>("AmenityId")
                        .HasColumnType("text")
                        .HasColumnName("amenity_id");

                    b.HasKey("RoomId", "AmenityId")
                        .HasName("room_amenities_room_id_amenity_id_pk");

                    b.HasIndex("AmenityId");

                    b.ToTable("room_amenities", (string)null);
                });

            modelBuilder.Entity("Hotel.Api.Data.SnapshotJob", b =>
                {
                    b.Property<string>("Path")
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("DesiredVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("desired_version");

                    b.Property<DateTime?>("LeasedUntil")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("leased_until");

                    b.Property<DateTime>("NextAttemptAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("next_attempt_at");

                    b.HasKey("Path");

                    b.ToTable("snapshot_jobs", (string)null);
                });

            modelBuilder.Entity("Hotel.Api.Data.Hotel", b =>
                {
                    b.HasOne("Hotel.Api.Data.Destination", null)
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired()
                        .HasConstraintName("hotels_destination_id_destinations_id_fk");
                });

            modelBuilder.Entity("Hotel.Api.Data.HotelAmenity", b =>
                {
                    b.HasOne("Hotel.Api.Data.Amenity", null)
                        .WithMany()
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("hotel_amenities_amenity_id_amenities_id_fk");

                    b.HasOne("Hotel.Api.Data.Hotel", null)
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("hotel_amenities_hotel_id_hotels_id_fk");
                });

            modelBuilder.Entity("Hotel.Api.Data.HotelFact", b =>
                {
                    b.HasOne("Hotel.Api.Data.Hotel", null)
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("hotel_facts_hotel_id_hotels_id_fk");
                });

            modelBuilder.Entity("Hotel.Api.Data.HotelFaq", b =>
                {
                    b.HasOne("Hotel.Api.Data.Hotel", null)
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("hotel_faqs_hotel_id_hotels_id_fk");
                });

            modelBuilder.Entity("Hotel.Api.Data.HotelGalleryImage", b =>
                {
                    b.HasOne("Hotel.Api.Data.Hotel", null)
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("hotel_gallery_images_hotel_id_hotels_id_fk");

                    b.HasOne("Hotel.Api.Data.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("hotel_gallery_images_room_id_rooms_id_fk");
                });

            modelBuilder.Entity("Hotel.Api.Data.HotelHighlight", b =>
                {
                    b.HasOne("Hotel.Api.Data.Hotel", null)
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("hotel_highlights_hotel_id_hotels_id_fk");
                });

            modelBuilder.Entity("Hotel.Api.Data.HotelNearbyPlace", b =>
                {
                    b.HasOne("Hotel.Api.Data.Hotel", null)
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("hotel_nearby_places_hotel_id_hotels_id_fk");
                });

            modelBuilder.Entity("Hotel.Api.Data.HotelPolicy", b =>
                {
                    b.HasOne("Hotel.Api.Data.Hotel", null)
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("hotel_policies_hotel_id_hotels_id_fk");
                });

            modelBuilder.Entity("Hotel.Api.Data.HotelReview", b =>
                {
                    b.HasOne("Hotel.Api.Data.Hotel", null)
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("hotel_reviews_hotel_id_hotels_id_fk");

                    b.HasOne("Hotel.Api.Data.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("hotel_reviews_room_id_rooms_id_fk");
                });

            modelBuilder.Entity("Hotel.Api.Data.HotelReviewScore", b =>
                {
                    b.HasOne("Hotel.Api.Data.Hotel", null)
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("hotel_review_scores_hotel_id_hotels_id_fk");
                });

            modelBuilder.Entity("Hotel.Api.Data.Inquiry", b =>
                {
                    b.HasOne("Hotel.Api.Data.Hotel", null)
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired()
                        .HasConstraintName("inquiries_hotel_id_hotels_id_fk");

                    b.HasOne("Hotel.Api.Data.Offer", null)
                        .WithMany()
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .HasConstraintName("inquiries_offer_id_offers_id_fk");

                    b.HasOne("Hotel.Api.Data.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .HasConstraintName("inquiries_room_id_rooms_id_fk");
                });

            modelBuilder.Entity("Hotel.Api.Data.Offer", b =>
                {
                    b.HasOne("Hotel.Api.Data.Hotel", null)
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("offers_hotel_id_hotels_id_fk");
                });

            modelBuilder.Entity("Hotel.Api.Data.Room", b =>
                {
                    b.HasOne("Hotel.Api.Data.Hotel", null)
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("rooms_hotel_id_hotels_id_fk");
                });

            modelBuilder.Entity("Hotel.Api.Data.RoomAmenity", b =>
                {
                    b.HasOne("Hotel.Api.Data.Amenity", null)
                        .WithMany()
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("room_amenities_amenity_id_amenities_id_fk");

                    b.HasOne("Hotel.Api.Data.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("room_amenities_room_id_rooms_id_fk");
                });
#pragma warning restore 612, 618
        }
    }
}
