/**
 * Generates responsive AVIF/WebP variants for every source image in
 * `apps/api/wwwroot/images/` and writes `apps/api/ClientApp/src/lib/image-manifest.ts`.
 *
 * Variant filenames embed a content hash so they can be served with a long
 * `immutable` cache lifetime without ever going stale. Generated files are
 * committed; run this only when a source image is added or changed. Re-running
 * is cheap: only missing variants are encoded, and stale ones are pruned.
 */
import { createHash } from 'node:crypto'
import { mkdir, readdir, readFile, unlink, writeFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { join } from 'node:path'

import sharp from 'sharp'

const sourceDir = 'apps/api/wwwroot/images'
const outputDir = join(sourceDir, 'gen')
const manifestPath = 'apps/api/ClientApp/src/lib/image-manifest.ts'
const widths = [320, 420, 540, 672, 768, 960, 1120, 1280, 1600, 1920]

/** Legacy fixed-size exports superseded by the generated variants. */
const skip = new Set(['hero-1440.avif', 'hero-1920.avif', 'hero-source.png'])

type ManifestEntry = {
  width: number
  height: number
  src: string
  avif: string
  webp: string
}

function renderManifest(manifest: Record<string, ManifestEntry>) {
  const entries = Object.entries(manifest)
    .map(([key, value]) => `  '${key}': ${JSON.stringify(value)},`)
    .join('\n')

  return `// Generated by scripts/generate-images.ts. Do not edit by hand.
export type ImageVariants = {
  width: number
  height: number
  src: string
  avif: string
  webp: string
}

// Partial: callers may pass sources with no pre-built variants (admin uploads).
export const imageManifest: Partial<Record<string, ImageVariants>> = {
${entries}
}
`
}

async function main() {
  await mkdir(outputDir, { recursive: true })

  const files = (await readdir(sourceDir))
    .filter((file) => /\.(png|jpg|jpeg|webp)$/.test(file))
    .filter((file) => !skip.has(file))
    .sort()

  const manifest: Record<string, ManifestEntry> = {}
  const expected = new Set<string>()
  let encoded = 0

  for (const file of files) {
    const buffer = await readFile(join(sourceDir, file))
    const hash = createHash('sha256').update(buffer).digest('hex').slice(0, 8)
    const base = file.replace(/\.[^.]+$/, '')
    const { width = 0, height = 0 } = await sharp(buffer).metadata()
    const targets = widths.filter((w) => w < width).concat(width)

    const avif: string[] = []
    const webp: string[] = []

    for (const target of targets) {
      const avifName = `${base}-${target}.${hash}.avif`
      const webpName = `${base}-${target}.${hash}.webp`
      expected.add(avifName)
      expected.add(webpName)

      if (!existsSync(join(outputDir, avifName))) {
        await writeFile(
          join(outputDir, avifName),
          await sharp(buffer)
            .resize({ width: target })
            .avif({ quality: 55, effort: 6 })
            .toBuffer(),
        )
        encoded++
      }
      if (!existsSync(join(outputDir, webpName))) {
        await writeFile(
          join(outputDir, webpName),
          await sharp(buffer)
            .resize({ width: target })
            .webp({ quality: 72, effort: 6 })
            .toBuffer(),
        )
        encoded++
      }

      avif.push(`/images/gen/${avifName} ${target}w`)
      webp.push(`/images/gen/${webpName} ${target}w`)
    }

    manifest[`/images/${file}`] = {
      width,
      height,
      // Fallback `src` points at a hashed variant so it is cacheable too.
      src: `/images/gen/${base}-${targets.at(-1)}.${hash}.webp`,
      avif: avif.join(', '),
      webp: webp.join(', '),
    }
  }

  // Prune variants left behind by a removed or edited source image.
  let pruned = 0
  for (const file of await readdir(outputDir)) {
    if (expected.has(file)) continue
    await unlink(join(outputDir, file))
    pruned++
  }

  const next = renderManifest(manifest)
  const current = existsSync(manifestPath)
    ? await readFile(manifestPath, 'utf8')
    : ''
  if (current !== next) await writeFile(manifestPath, next)

  console.log(
    `images: ${files.length} sources, ${expected.size} variants ` +
      `(${encoded} encoded, ${pruned} pruned), manifest ` +
      `${current === next ? 'unchanged' : 'updated'}`,
  )
}

await main()
